### ISSUE TITLE
Vitals check error

### ISSUE THREAD

**Issue by aidanthewiz** [legraphista/ffmpeg-progress-wrapper#10]
`Vitals check for PID:3043 resulted in: Error: ESRCH: no such process, read
`
I get this error posted to stderr four times using this code;

```javascript
await (async () => {
	const process = new FFMpegProgress(ffmpegOptions);
	process.once('details', (details) => console.log(JSON.stringify(details)));
	process.on('progress', (progress) => {
		let formattedTime = new Date(progress.eta).toISOString().substr(11, 8);
		console.log("ETA of " + eventObject.s3.object.key + " is " + formattedTime);
		const date = Date.now();
		let currentDate = null;
		do {
			currentDate = Date.now();
		} while (currentDate - date < 5000);
	});
	process.once('end', console.log.bind(console, 'ffmpeg finished and exited with code'));
	await process.onDone();
})();
```

**Comment by legraphista** [comment]
The module uses `vitals` to check on the ffmpeg's memory usage in order to terminate it if the memory is above a set threshold.

For that to happen, `vitals` queues up a couple of tasks on node's event loop, but by looking at your code, you block the event loop for up to 5 seconds each time there's a `progress` update. 

If there had been `vitals` checks queued up before the event loop has been blocked and the ffmpeg progress finished before the event loop had been unblocked, then the checks will fail because the process no longer exists.

I suggest checking this talk about the JS event loop https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by aidanthewiz** [comment]
Makes sense, thanks for the link! Is there the possibility of adding a way to decrease the time the loop logs without doing my delay workaround that doesn't cause the vital's queue to become out of sync?

**Comment by legraphista** [comment]
```javascript
await (async () => {
	const process = new FFMpegProgress(ffmpegOptions);
	process.once('details', (details) => console.log(JSON.stringify(details)));

	let lastUpdate = 0;

	process.on('progress', (progress) => {
		const now = Date.now();
		
		if (now - lastUpdate < 5000) {
			return;
		}
		lastUpdate = now; 

		let formattedTime = new Date(progress.eta).toISOString().substr(11, 8);
		console.log("ETA of " + eventObject.s3.object.key + " is " + formattedTime);
	});
	process.once('end', console.log.bind(console, 'ffmpeg finished and exited with code'));
	await process.onDone();
})();
```

**Comment by aidanthewiz** [comment]
Works perfectly, thank you!

**Comment by legraphista** [comment]
Glad I could help!
