### ISSUE TITLE
filter_complex doesnt seem to run.

### ISSUE THREAD

**Issue by samueleastdev** [legraphista/ffmpeg-progress-wrapper#11]
Hi 

This maybe something I am doing wrong but take the following code.

~~~
const { FFMpegProgress } = require('ffmpeg-progress-wrapper');

let media = ['/Users/username/Desktop/video1.mp4', '/Users/username/Desktop/video2.mp4']

// Setup the combine command
let inputs = '';

let filter = '';

let length = media.length;

let args = [];

for (let a = 0; a < media.length; a++) {

    args.push('-i');

    args.push(media[a]);

    filter += '[' + a + ':v:0][' + a + ':a:0]';

}

args.push('-filter_complex');

args.push('"' + filter + 'concat=n=' + length + ':v=1:a=1[outv][outa]' + '"');

args.push('-map');

args.push('"[outv]"');

args.push('-map');

args.push('"[outa]"');

args.push('/Users/username/Desktop/combined.mkv');

try {

    console.log('FFMpegProgress', args.join(' '));

    const process = new FFMpegProgress(args, {
        cmd: '/usr/local/bin/ffmpeg'
    });

    process.on('progress', (data) => {

        var progress = Math.round(data.progress * 100);

        console.log('progress', progress);

    });

    process.on('end', () => {

        console.log('Finished');

    });

} catch (error) {

    console.log(error)

}
~~~

If you run this with node it just finishes and does not run the command through FFMpegProgress.

But if you take the outputted command from the console.log and paste it into terminal and run it the process will run without issues.

~~~
FFMpegProgress -i /Users/username/Desktop/video1.mp4 -i /Users/username/Desktop/video2.mp4 -filter_complex "[0:v:0][0:a:0][1:v:0][1:a:0]concat=n=2:v=1:a=1[outv][outa]" -map "[outv]" -map "[outa]" /Users/username/Desktop/combined.mkv
~~~

Not sure if it is something to do with how the double quotes etc are being escaped.

Any suggestions?

Thanks

**Comment by legraphista** [comment]
Hi @samueleastdev 

Quotes are used for shell commands, they are not needed in here. `FFMpegProgress` uses `spawn` at its core.
I've re-written your example with some fixes:
```javascript

const { FFMpegProgress } = require('ffmpeg-progress-wrapper');

(async () => {

  let media = ['./video1.mp4', './video2.mp4']
  let length = media.length;

  let filterStepHeader = '';
  let args = [];

  for (let a = 0; a < media.length; a++) {
    args.push('-i');
    args.push(media[a]);

    filterStepHeader += '[' + a + ':v:0][' + a + ':a:0]';
  }

  args.push('-filter_complex');

  args.push(`${filterStepHeader} concat=n=${length}:v=1:a=1 [outv][outa]`);

  args.push('-map');
  args.push('[outv]');

  args.push('-map');
  args.push('[outa]');

  args.push('./combined.mkv');
  args.push('-y');

  try {

    const process = new FFMpegProgress(args, {
      cmd: '/usr/local/bin/ffmpeg',
      // both video1 & video2 are 10 seconds, combined they are 20 seconds
      duration: 20
    });

    process.on('progress', (data) => {
      console.log('progress', (data.progress * 100).toFixed(2) + '%');
    });

    await process.onDone();

    console.log('Finished');

  } catch (error) {
    console.log(error)
  }

})().then(console.log).catch(console.error);

```

The main issues were that:
- the try-catch was doing nothing, since `FFMpegProgress` is async
- awaiting `.onDone()` (or using `.onDone().then()` if you're into promises) can be used to know when the process finished (also awaiting `.onDone()` would have surfaced the quote error)
- when you're just transcoding, we can determine the length of the output automatically, but when introducing `filter_complex` the length is undeterminable, so in order to have good ETA/progress % you need to provide the final output's `duration`

As a side note, you can determine the duration of your media by running `ffprobe -i video1.mp4 -of json -show_format -show_streams` beforehand (you can run it via `spawn` / `spawnSync`)
- `-of json` will output a json to stdout 
- `-show_format` will output the container format (you usually find the duration there)
- `-show_streams` will output an array of data for each video/audio/data/subtitle stream (where you can also find duration too)

When in doubt, you can also add `process.on('raw', console.log);` to your code to output the info from the `ffmpeg` process

**Comment by samueleastdev** [comment]
Thanks @legraphista really appreciate the response love this tool super useful.

I was just messing around trying to clip and combine videos.

Here is as far as I’ve got.

https://github.com/samueleastdev/ffmpeg-combining-ads

Combining/concatenating is a bit of a pain with FFmpeg 👍🏻
